import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './component/Client/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tech Blog',
  description: 'Generated by create next app',
  keywords: 'blogs, tech , tech-blogs , techblog ,   ',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
